### ISSUE TITLE
failure when running on a category with more than two values

### ISSUE THREAD

**Issue by gregcaporaso** [mortonjt/q2-composition#5]
using the test artifacts that I sent to @mortonjt by email, i get the following for a category with three values:

```bash
$ qiime composition ancom --i-table composition-table.qza --m-metadata-file sample-metadata.tsv --m-metadata-category treatment-group --o-visualization ancom-out && qiime tools view ancom-out.qzv
Traceback (most recent call last):
  File "/Users/caporaso/miniconda3/envs/qiime2-dev/bin/qiime", line 11, in <module>
    load_entry_point('q2cli', 'console_scripts', 'qiime')()
  File "/Users/caporaso/miniconda3/envs/qiime2-dev/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/caporaso/miniconda3/envs/qiime2-dev/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/caporaso/miniconda3/envs/qiime2-dev/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/caporaso/miniconda3/envs/qiime2-dev/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/caporaso/miniconda3/envs/qiime2-dev/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/caporaso/miniconda3/envs/qiime2-dev/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/caporaso/Google Drive/code/qiime2/q2cli/q2cli/commands.py", line 154, in __call__
    results = self.action(**arguments)
  File "<decorator-gen-191>", line 2, in ancom
  File "/Users/caporaso/Google Drive/code/qiime2/qiime2/qiime/core/callable.py", line 238, in callable_wrapper
    output_types, provenance)
  File "/Users/caporaso/Google Drive/code/qiime2/qiime2/qiime/core/callable.py", line 438, in _callable_executor_
    ret_val = callable(output_dir=temp_dir, **view_args)
  File "/Users/caporaso/Google Drive/code/qiime2/q2-composition/q2_composition/_ancom.py", line 71, in ancom
    transform_function, difference_function)
  File "/Users/caporaso/Google Drive/code/qiime2/q2-composition/q2_composition/_ancom.py", line 112, in _volcanoplot
    fold_change = transformed_table.apply(difference_function, axis=0)
  File "/Users/caporaso/miniconda3/envs/qiime2-dev/lib/python3.5/site-packages/pandas/core/frame.py", line 4061, in apply
    return self._apply_standard(f, axis, reduce=reduce)
  File "/Users/caporaso/miniconda3/envs/qiime2-dev/lib/python3.5/site-packages/pandas/core/frame.py", line 4157, in _apply_standard
    results[i] = func(v)
  File "/Users/caporaso/Google Drive/code/qiime2/q2-composition/q2_composition/_ancom.py", line 109, in <lambda>
    difference_function = lambda x: _d_func(*[x[metadata==c] for c in cats])
TypeError: ('<lambda>() takes 1 positional argument but 3 were given', 'occurred at index GCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATCTGATACTGGCAAGCTTGAGTCTCGTA')
```

**Comment by mortonjt** [comment]
This is being addressed in #7
